export enum WorkingParamsStatusEnum {
  UNKNOW = 'UNKNOW',
  REQUEST_IN_PROGRESS = 'REQUEST_IN_PROGRESS',
  PARAMETERS_SET_CORRECTLY = 'PARAMETERS_SET_CORRECTLY',
  PARAMETERS_SET_ERROR = 'PARAMETERS_SET_ERROR',
  PARAMETERS_TURN_OFF = 'PARAMETERS_TURN_OFF',
}
export type WorkingParamsStatus = WorkingParamsStatusEnum;